# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biblioteca_page2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

'''

Este arquivo é parte do programa Buiatric Care Neurology

Buiatric Care Neurology é um software livre; você pode redistribuí-lo e/ou
modificá-lo dentro dos termos da Licença Pública Geral GNU como
publicada pela Fundação do Software Livre (FSF); na versão 3 da
Licença, ou (a seu critério) qualquer versão posterior.

Este programa é distribuído na esperança de que possa ser  útil,
mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO
a qualquer MERCADO ou APLICAÇÃO EM PARTICULAR. Veja a
Licença Pública Geral GNU para maiores detalhes.

Você deve ter recebido uma cópia da Licença Pública Geral GNU junto
com este programa, Se não, veja <http://www.gnu.org/licenses/>.

'''


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(665, 609)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/bcicone.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_3 = QtWidgets.QScrollArea(Form)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_3.setPalette(palette)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 622, 508))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.botao_int_aspergillus = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_int_aspergillus.setFont(font)
        self.botao_int_aspergillus.setObjectName("botao_int_aspergillus")
        self.verticalLayout_3.addWidget(self.botao_int_aspergillus)
        self.botao_int_chumbo = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_int_chumbo.setFont(font)
        self.botao_int_chumbo.setObjectName("botao_int_chumbo")
        self.verticalLayout_3.addWidget(self.botao_int_chumbo)
        self.botao_int_claviceps = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_claviceps.setFont(font)
        self.botao_int_claviceps.setObjectName("botao_int_claviceps")
        self.verticalLayout_3.addWidget(self.botao_int_claviceps)
        self.botao_int_equisetum = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_equisetum.setFont(font)
        self.botao_int_equisetum.setObjectName("botao_int_equisetum")
        self.verticalLayout_3.addWidget(self.botao_int_equisetum)
        self.botao_int_ipasarifolia = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_ipasarifolia.setFont(font)
        self.botao_int_ipasarifolia.setObjectName("botao_int_ipasarifolia")
        self.verticalLayout_3.addWidget(self.botao_int_ipasarifolia)
        self.botao_int_ipcarnea = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_ipcarnea.setFont(font)
        self.botao_int_ipcarnea.setObjectName("botao_int_ipcarnea")
        self.verticalLayout_3.addWidget(self.botao_int_ipcarnea)
        self.botao_int_marsdenia = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_marsdenia.setFont(font)
        self.botao_int_marsdenia.setObjectName("botao_int_marsdenia")
        self.verticalLayout_3.addWidget(self.botao_int_marsdenia)
        self.botao_int_orgcarb = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_orgcarb.setFont(font)
        self.botao_int_orgcarb.setObjectName("botao_int_orgcarb")
        self.verticalLayout_3.addWidget(self.botao_int_orgcarb)
        self.botao_int_phalaris = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_phalaris.setFont(font)
        self.botao_int_phalaris.setObjectName("botao_int_phalaris")
        self.verticalLayout_3.addWidget(self.botao_int_phalaris)
        self.botao_int_polygala = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_polygala.setFont(font)
        self.botao_int_polygala.setObjectName("botao_int_polygala")
        self.verticalLayout_3.addWidget(self.botao_int_polygala)
        self.botao_int_prosopis = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_prosopis.setFont(font)
        self.botao_int_prosopis.setObjectName("botao_int_prosopis")
        self.verticalLayout_3.addWidget(self.botao_int_prosopis)
        self.botao_int_ricinus = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_ricinus.setFont(font)
        self.botao_int_ricinus.setObjectName("botao_int_ricinus")
        self.verticalLayout_3.addWidget(self.botao_int_ricinus)
        self.botao_int_sida = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_sida.setFont(font)
        self.botao_int_sida.setObjectName("botao_int_sida")
        self.verticalLayout_3.addWidget(self.botao_int_sida)
        self.botao_int_solanum = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_solanum.setFont(font)
        self.botao_int_solanum.setObjectName("botao_int_solanum")
        self.verticalLayout_3.addWidget(self.botao_int_solanum)
        self.botao_int_sternocarpella = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_int_sternocarpella.setFont(font)
        self.botao_int_sternocarpella.setObjectName("botao_int_sternocarpella")
        self.verticalLayout_3.addWidget(self.botao_int_sternocarpella)
        self.botao_int_ureia = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_int_ureia.setFont(font)
        self.botao_int_ureia.setObjectName("botao_int_ureia")
        self.verticalLayout_3.addWidget(self.botao_int_ureia)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_3, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 9, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/logo3.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollArea_4 = QtWidgets.QScrollArea(Form)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_4.setPalette(palette)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 639, 69))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.botao_babesiose = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_babesiose.setFont(font)
        self.botao_babesiose.setObjectName("botao_babesiose")
        self.verticalLayout_4.addWidget(self.botao_babesiose)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea_4, 12, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea.setPalette(palette)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 622, 136))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.botao_cetose = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_cetose.setFont(font)
        self.botao_cetose.setObjectName("botao_cetose")
        self.verticalLayout.addWidget(self.botao_cetose)
        self.botao_cobre = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_cobre.setFont(font)
        self.botao_cobre.setObjectName("botao_cobre")
        self.verticalLayout.addWidget(self.botao_cobre)
        self.botao_hipocalcemia = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_hipocalcemia.setFont(font)
        self.botao_hipocalcemia.setObjectName("botao_hipocalcemia")
        self.verticalLayout.addWidget(self.botao_hipocalcemia)
        self.botao_poliencefalomalacia = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_poliencefalomalacia.setFont(font)
        self.botao_poliencefalomalacia.setObjectName("botao_poliencefalomalacia")
        self.verticalLayout.addWidget(self.botao_poliencefalomalacia)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 5, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(Form)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 255, 254))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea_2.setPalette(palette)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 622, 291))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.botao_aujeszky = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_aujeszky.setFont(font)
        self.botao_aujeszky.setObjectName("botao_aujeszky")
        self.verticalLayout_2.addWidget(self.botao_aujeszky)
        self.botao_botulismo = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_botulismo.setFont(font)
        self.botao_botulismo.setObjectName("botao_botulismo")
        self.verticalLayout_2.addWidget(self.botao_botulismo)
        self.botao_encefalopatia = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_encefalopatia.setFont(font)
        self.botao_encefalopatia.setObjectName("botao_encefalopatia")
        self.verticalLayout_2.addWidget(self.botao_encefalopatia)
        self.botao_febrecatarral = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.botao_febrecatarral.setFont(font)
        self.botao_febrecatarral.setObjectName("botao_febrecatarral")
        self.verticalLayout_2.addWidget(self.botao_febrecatarral)
        self.botao_leucose = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_leucose.setFont(font)
        self.botao_leucose.setObjectName("botao_leucose")
        self.verticalLayout_2.addWidget(self.botao_leucose)
        self.botao_listeriose = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_listeriose.setFont(font)
        self.botao_listeriose.setObjectName("botao_listeriose")
        self.verticalLayout_2.addWidget(self.botao_listeriose)
        self.botao_meningoecefalite = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_meningoecefalite.setFont(font)
        self.botao_meningoecefalite.setObjectName("botao_meningoecefalite")
        self.verticalLayout_2.addWidget(self.botao_meningoecefalite)
        self.botao_raiva = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_raiva.setFont(font)
        self.botao_raiva.setObjectName("botao_raiva")
        self.verticalLayout_2.addWidget(self.botao_raiva)
        self.botao_tetano = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.botao_tetano.setFont(font)
        self.botao_tetano.setObjectName("botao_tetano")
        self.verticalLayout_2.addWidget(self.botao_tetano)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 8, 0, 1, 1)


        self.botao_int_aspergillus.clicked.connect(self.comando_aspergillus)
        self.botao_int_chumbo.clicked.connect(self.comando_chumbo)
        self.botao_int_claviceps.clicked.connect(self.comando_claviceps)
        self.botao_int_equisetum.clicked.connect(self.comando_equisetum)
        self.botao_int_ipasarifolia.clicked.connect(self.comando_ipasarifolia)
        self.botao_int_ipcarnea.clicked.connect(self.comando_ipcarnea)
        self.botao_int_marsdenia.clicked.connect(self.comando_marsdenia)
        self.botao_int_marsdenia.clicked.connect(self.comando_marsdenia)
        self.botao_int_phalaris.clicked.connect(self.comando_phalaris)
        self.botao_int_polygala.clicked.connect(self.comando_polygala)
        self.botao_int_prosopis.clicked.connect(self.comando_prosopis)
        self.botao_int_ricinus.clicked.connect(self.comando_ricinus)
        self.botao_int_sida.clicked.connect(self.comando_sida)
        self.botao_int_solanum.clicked.connect(self.comando_solanum)
        self.botao_int_sternocarpella.clicked.connect(self.comando_sternocarpella)
        self.botao_int_ureia.clicked.connect(self.comando_ureia)
        self.botao_babesiose.clicked.connect(self.comando_babesiose)
        self.botao_cetose.clicked.connect(self.comando_cetose)
        self.botao_cobre.clicked.connect(self.comando_cobre)
        self.botao_hipocalcemia.clicked.connect(self.comando_hipocalcemia)
        self.botao_poliencefalomalacia.clicked.connect(self.comando_poliencefalomalacia)
        self.botao_aujeszky.clicked.connect(self.comando_aujeszky)
        self.botao_botulismo.clicked.connect(self.comando_botulismo)
        self.botao_encefalopatia.clicked.connect(self.comando_encefalopatia)
        self.botao_febrecatarral.clicked.connect(self.comando_febrecatarral)
        self.botao_leucose.clicked.connect(self.comando_leucose)
        self.botao_listeriose.clicked.connect(self.comando_listeriose)
        self.botao_meningoecefalite.clicked.connect(self.comando_meningoecefalite)
        self.botao_raiva.clicked.connect(self.comando_raiva)
        self.botao_tetano.clicked.connect(self.comando_tetano)



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def comando_aspergillus(self):
        os.startfile("artigos\\aspergillus.pdf")

    def comando_chumbo(self):
        os.startfile("artigos\\chumbo.pdf")

    def comando_claviceps(self):
        os.startfile("artigos\\claviceps.pdf")

    def comando_equisetum(self):
        os.startfile("artigos\\equisetum.pdf")

    def comando_ipasarifolia(self):
        os.startfile("artigos\\ipasarifolia.pdf")

    def comando_ipcarnea(self):
        os.startfile("artigos\\ipcarnea.pdf")

    def comando_marsdenia(self):
        os.startfile("artigos\\marsdenia.pdf")

    def comando_orgcarb(self):
        os.startfile("artigos\\orgcarb.pdf")

    def comando_phalaris(self):
        os.startfile("artigos\\phalaris.pdf")

    def comando_polygala(self):
        os.startfile("artigos\\polygala.pdf")

    def comando_prosopis(self):
        os.startfile("artigos\\prosopis.pdf")

    def comando_ricinus(self):
        os.startfile("artigos\\ricinus.pdf")

    def comando_sida(self):
        os.startfile("artigos\\sida.pdf")

    def comando_solanum(self):
        os.startfile("artigos\\solanum.pdf")

    def comando_sternocarpella(self):
        os.startfile("artigos\\sternocarpella.pdf")

    def comando_ureia(self):
        os.startfile("artigos\\ureia.pdf")

    def comando_babesiose(self):
        os.startfile("artigos\\babesiose.pdf")

    def comando_cetose(self):
        os.startfile("artigos\\cetose.pdf")

    def comando_cobre(self):
        os.startfile("artigos\\cobre.pdf")

    def comando_hipocalcemia(self):
        os.startfile("artigos\\hipocalcemia.pdf")

    def comando_poliencefalomalacia(self):
        os.startfile("artigos\\poliencefalomalacia.pdf")

    def comando_aujeszky(self):
        os.startfile("artigos\\aujeszky.pdf")

    def comando_botulismo(self):
        os.startfile("artigos\\botulismo.pdf")

    def comando_encefalopatia(self):
        os.startfile("artigos\\encefalopatia.pdf")

    def comando_febrecatarral(self):
        os.startfile("artigos\\febrecatarral.pdf")

    def comando_leucose(self):
        os.startfile("artigos\\leucose.pdf")

    def comando_listeriose(self):
        os.startfile("artigos\\listeriose.pdf")

    def comando_meningoecefalite(self):
        os.startfile("artigos\\meningoecefalite.pdf")

    def comando_raiva(self):
        os.startfile("artigos\\raiva.pdf")

    def comando_tetano(self):
        os.startfile("artigos\\tetano.pdf")


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Buiatric Care - Diseases library"))
        self.botao_int_aspergillus.setText(_translate("Form", "Intoxication by Aspergillus clavatus"))
        self.botao_int_chumbo.setText(_translate("Form", "Intoxication by Lead"))
        self.botao_int_claviceps.setText(_translate("Form", "Intoxication by Claviceps paspalis"))
        self.botao_int_equisetum.setText(_translate("Form", "Intoxication by Equisetum"))
        self.botao_int_ipasarifolia.setText(_translate("Form", "Intoxication by Ipomoea asarifolia"))
        self.botao_int_ipcarnea.setText(_translate("Form", "Intoxication by ipomoea carnea"))
        self.botao_int_marsdenia.setText(_translate("Form", "Intoxication by Marsdenia"))
        self.botao_int_orgcarb.setText(_translate("Form", "Intoxication by organophosphates and carbamates"))
        self.botao_int_phalaris.setText(_translate("Form", "Intoxication by Phalaris"))
        self.botao_int_polygala.setText(_translate("Form", "Intoxication by Polygala klotzschii"))
        self.botao_int_prosopis.setText(_translate("Form", "Intoxication by Prosopis juriflora"))
        self.botao_int_ricinus.setText(_translate("Form", "Intoxication by Ricinus communis"))
        self.botao_int_sida.setText(_translate("Form", "Intoxication by Sida carpinifolia"))
        self.botao_int_solanum.setText(_translate("Form", "Intoxication by Solanum fastigiatum"))
        self.botao_int_sternocarpella.setText(_translate("Form", "Intoxication by Sternocarpella Maydis"))
        self.botao_int_ureia.setText(_translate("Form", "Intoxication by urea"))
        self.label_5.setText(_translate("Form", "Metabolic and nutritional diseases"))
        self.label_2.setText(_translate("Form", "Diseases caused by intoxication and toxic plants"))
        self.label_3.setText(_translate("Form", "Diseases caused by bacteria, toxins and viruses"))
        self.label_4.setText(_translate("Form", "Diseases library"))
        self.botao_babesiose.setText(_translate("Form", "Cerebral babesiosis"))
        self.label_6.setText(_translate("Form", "Parasitic diseases"))
        self.botao_cetose.setText(_translate("Form", "Ketosis"))
        self.botao_cobre.setText(_translate("Form", "Copper deficiency"))
        self.botao_hipocalcemia.setText(_translate("Form", "Hypocalcemia"))
        self.botao_poliencefalomalacia.setText(_translate("Form", "Poliencephalomalacia"))
        self.botao_aujeszky.setText(_translate("Form", "Aujeszkys disease"))
        self.botao_botulismo.setText(_translate("Form", "Botulism"))
        self.botao_encefalopatia.setText(_translate("Form", "Bovine spongiform encephalopathy"))
        self.botao_febrecatarral.setText(_translate("Form", "Malignant catarrhal fever"))
        self.botao_leucose.setText(_translate("Form", "Bovine leukosis"))
        self.botao_listeriose.setText(_translate("Form", "Listeriosis"))
        self.botao_meningoecefalite.setText(_translate("Form", "BHV-5 Meningoencephalitis"))
        self.botao_raiva.setText(_translate("Form", "Rabies"))
        self.botao_tetano.setText(_translate("Form", "Tetanus"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
